project:
  type: website
  output-dir: C:/Users/kenzthom.stu/OneDrive - UBC/GIT/E-Portfolio

website:
  title: "Mackenzie Thomson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: content.qmd
        text: Content & Deliverables
      - href: map_gallery.qmd
        text: Map Gallery
      - href: contact.qmd
        text: Contact Info

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual

